version: '2'
services:
  db:
    image: postgres:9.5

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/vishu_app
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  bundle: {}
